# Generated by Django 3.2.12 on 2022-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.ImageField(default='Dm.jpg', upload_to='person'),
        ),
    ]
