# Generated by Django 3.2.12 on 2022-02-16 10:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(default='Dm.jpg', upload_to=app.models.create_path),
        ),
    ]
